In [1]:
from sdv.single_table import TVAESynthesizer

In [2]:
from sdv.datasets.demo import download_demo

real_data, metadata = download_demo(
    modality='single_table',
    dataset_name='fake_hotel_guests'
)

In [7]:
real_data

,guest_email,has_rewards,room_type,amenities_fee,checkin_date,checkout_date,room_rate,billing_address,credit_card_number
0,michaelsanders@shaw.net,False,BASIC,37.89,27 Dec 2020,29 Dec 2020,131.23,"49380 Rivers Street\nSpencerville, AK 68265",4075084747483975747
1,randy49@brown.biz,False,BASIC,24.37,30 Dec 2020,02 Jan 2021,114.43,"88394 Boyle Meadows\nConleyberg, TN 22063",180072822063468
2,webermelissa@neal.com,True,DELUXE,0.00,17 Sep 2020,18 Sep 2020,368.33,"0323 Lisa Station Apt. 208\nPort Thomas, LA 82585",38983476971380
3,gsims@terry.com,False,BASIC,NaN,28 Dec 2020,31 Dec 2020,115.61,"77 Massachusetts Ave\nCambridge, MA 02139",4969551998845740
4,misty33@smith.biz,False,BASIC,16.45,05 Apr 2020,NaN,122.41,"1234 Corporate Drive\nBoston, MA 02116",3558512986488983
...,...,...,...,...,...,...,...,...,...
495,laurabennett@jones-duncan.net,False,BASIC,8.71,04 Jan 2021,06 Jan 2021,103.25,"5678 Office Road\nSan Francisco, CA 94103",3505516387300030
496,johnny71@cook.info,False,BASIC,16.31,24 Aug 2020,26 Aug 2020,115.81,"953 White Island\nChristopherside, TN 91366",2224524502892552
497,ygarcia@ballard-lopez.net,False,BASIC,30.59,11 Nov 2020,13 Nov 2020,141.61,"5678 Office Road\nSan Francisco, CA 94103",180096250673548
498,thomasdale@hall.com,False,BASIC,1.93,16 Jul 2020,18 Jul 2020,136.92,"5678 Office Road\nSan Francisco, CA 94103",4488223821722
499,danieltaylor@harper.com,False,BASIC,3.84,22 Mar 2020,25 Mar 2020,143.52,"034 Tran Oval\nHowardshire, VT 40933",213165812201188

In [4]:
synthesizer = TVAESynthesizer(metadata)
synthesizer.fit(real_data)

In [5]:
synthetic_data = synthesizer.sample(num_rows=500)

In [6]:
synthetic_data

,guest_email,has_rewards,room_type,amenities_fee,checkin_date,checkout_date,room_rate,billing_address,credit_card_number
0,cheryl93@example.com,False,BASIC,12.06,28 May 2020,20 Jul 2020,126.64,"093 Williams Lane Apt. 170\nNorth Charles, PA ...",180090934066211
1,sandersdarlene@example.org,False,BASIC,37.25,12 Nov 2020,24 Nov 2020,181.48,"PSC 5816, Box 0394\nAPO AA 74642",30083012986584
2,hsmith@example.org,False,BASIC,14.75,22 May 2020,16 Jun 2020,134.90,"819 Peck Curve Suite 448\nEast Johnmouth, WI 0...",2290394691481974
3,jonesernest@example.net,False,DELUXE,2.64,17 Feb 2020,03 Mar 2020,195.93,"82758 Huffman Isle Suite 101\nHumphreyview, KS...",4444812351068428276
4,pstanton@example.com,True,BASIC,1.70,22 Jan 2021,07 Dec 2020,191.64,"228 Fisher Fork\nSouth Mitchell, WA 81769",4875851017747494
...,...,...,...,...,...,...,...,...,...
495,gibsonian@example.net,False,BASIC,9.26,03 Jun 2020,21 Jul 2020,109.79,"970 Stacey Rapids\nTrujilloville, OH 69888",4596292898478
496,christopherbennett@example.net,False,BASIC,19.94,29 Nov 2020,04 Nov 2020,116.13,"45916 Gibson Crescent\nPort Brent, VT 60828",379715427058934
497,nshepherd@example.com,False,BASIC,14.60,09 Aug 2020,23 Aug 2020,121.68,"9536 Brittany Village Apt. 257\nSamuelside, MI...",36069260214278
498,michaelmoore@example.com,False,BASIC,0.82,19 Nov 2020,06 Dec 2020,149.01,"629 Torres Unions Suite 282\nTaraton, RI 30702",3572666755718905
499,fhoward@example.com,False,BASIC,23.93,16 Nov 2020,29 Jun 2020,117.16,"2250 Hill Common Apt. 871\nPort Katrinahaven, ...",2713334835086569

In [8]:
from sdv.evaluation.single_table import evaluate_quality

In [9]:
quality_report = evaluate_quality(
    real_data,
    synthetic_data,
    metadata
)

Creating report: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4/4 [00:00<00:00, 39.02it/s]

Overall Quality Score: 85.74%

Properties:
Column Shapes: 86.58%
Column Pair Trends: 84.9%